variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# 캐시 init
cache:
  stage: cache
  paths:
    - .m2/repository/
    - target/
  
  script:
    - echo -e 
        "
        $CI_JOB_STAGE; START\\n
        *****************************************\\n
        'Checking variables'\\n
        $MAVEN_CLI_OPTS     \\n
        $MAVEN_OPTS         \\n
        *****************************************\\n
        $CI_JOB_STAGE; END
        "
  only:
    - dist
    - pre_dist

# Java source 컴파일
compile:
  stage: compile

  script:
    - echo -e 
        "
        $CI_JOB_STAGE; START\\n
        *****************************************\\n
        'TRIGGER MAVEN COMPILE'
        "
    - mvn $MAVEN_CLI_OPTS compile
    - echo -e 
        "
        *****************************************\\n
        $CI_JOB_STAGE; END
        "
  only:
    - dist
    - pre_dist

# 유닛 테스트
# test:
#   stage: test
#   script:
#     - mvn $MAVEN_CLI_OPTS test

# frontend 빌드
build-frontend:
  stage: build-frontend

  script:
    - echo -e 
        "
        $CI_JOB_STAGE START\\n
        *****************************************\\n
        'INSTALL AND BUILD NODE PACKAGE VIA NPM'
        "
    - mvn $MAVEN_CLI_OPTS frontend:npm
    - echo -e 
        "
        *****************************************\\n
        $CI_JOB_STAGE END
        "
  only:
    - dist

# 리소스 copy to target
resource-copy:
  stage: resource-copy

  script:
    - echo -e 
        "
        $CI_JOB_STAGE START\\n
        *****************************************\n
        'COPY ALL RESOURCES INTO TARGET'
        "
    - mvn $MAVEN_CLI_OPTS resources:copy-resources
    - echo -e 
        "
        *****************************************\n
        $CI_JOB_STAGE END
        "
  only:
    - dist

# 패키징
package:
  stage: package

  script:
    - echo -e 
        "
        $CI_JOB_STAGE; START\\n
        *****************************************\n
        'MAKE JAR PACKAGE'
        "
    - mvn $MAVEN_CLI_OPTS package spring-boot:repackage
    - echo -e 
        "
        *****************************************\n
        $CI_JOB_STAGE; END
        "
  only:
    - dist

# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - dist