variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# 캐시 init
cache:
  paths:
    - .m2/repository/
    - target/

# Java source 컴파일
compile:
  stage: build

  script:
    - echo -e 
        "
        ***************************************** \n
        'TRIGGER MAVEN COMPILE'                   \n
        "
    - mvn $MAVEN_CLI_OPTS compile
    - echo -e 
        "
        ***************************************** \n
        "
  only:
    - dist
    - pre_dist

# 유닛 테스트
# test:
#   stage: test
#   script:
#     - mvn $MAVEN_CLI_OPTS test

# frontend 빌드
build-frontend:
  stage: build

  script:
    - echo -e 
        "
        ***************************************** \n
        'INSTALL AND BUILD NODE PACKAGE VIA NPM'  \n
        "
    - mvn $MAVEN_CLI_OPTS frontend:npm
    - echo -e 
        "
        ***************************************** \n
        "
  only:
    - dist

# 리소스 copy to target
resource-copy:
  stage: build

  script:
    - echo -e 
        "
        ***************************************** \n
        'COPY ALL RESOURCES INTO TARGET'          \n
        "
    - mvn $MAVEN_CLI_OPTS resources:copy-resources
    - echo -e 
        "
        ***************************************** \n
        $CI_JOB_STAGE END
        "
  only:
    - dist

# 패키징
package:
  stage: build

  script:
    - echo -e 
        "
        ***************************************** \n
        'MAKE JAR PACKAGE'                        \n
        "
    - mvn $MAVEN_CLI_OPTS package spring-boot:repackage
    - echo -e 
        "
        ***************************************** \n
        "
  only:
    - dist

# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - dist